### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by spiritelf** [yjmyzz/dubbox-sample#1]
Build file 'E:\dubbo\dubbox-sample\demo-service-consumer\build.gradle' line: 56
- What went wrong:
  A problem occurred evaluating project ':demo-service-consumer'.
  
  > Could not find property 'installDist' on project ':demo-service-consumer'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

**Comment by yjmyzz** [comment]
installDist是gradle 插件apply plugin: 'application' 自带的一个task，只要build.gradle里有apply plugin: 'application' 就有这个任务，你出现这个错误，说明你机器上application插件没下载成功，建议先搜索下gradle application plugin的用法
