### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by spiritelf** [yjmyzz/dubbox-sample#3]
怎么在本机windows进行测试啊？ 怎么配置生成bat的启动脚本啊

**Comment by yjmyzz** [comment]
xxx_provider 是服务提供方，先跑这个项目，相当于服务启动
xxx_consumer 是服务消费方，再跑这个项目，相当于服务调用

**Comment by spiritelf** [comment]
生成的linux下启动脚本？ 怎么配置成windows的？

**Comment by yjmyzz** [comment]
不提供windows环境的脚本，自己参考shell脚本的含义，翻译成windows下的bat吧

**Comment by spiritelf** [comment]
呵呵  有没有其他解决办法啊？
